apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-api-feed
  name: backend-api-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-api-feed